spring:
 datasource:
  url: jdbc:postgresql://localhost/social_network_service
  username: postgres
  password: 123456
 jpa:
  generate-ddl: true
  properties.hibernate.jdbc.lob.non_contextual_creation: true
 main:
  allow-bean-definition-overriding: true


security:
 oauth2:
  client:
   clientId: 255982088468-0d4dkgdrri5143egdf8vu1n724b2t2hb.apps.googleusercontent.com
   clientSecret: ${clientSecret}
   accessTokenUri: https://www.googleapis.com/oauth2/v4/token
   userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
   clientAuthenticationScheme: form
   scope: openid,email,profile
  resource:
   userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
   preferTokenInfo: true

server:
 port: 8080

